apiVersion: v1
kind: Service
metadata:
  name: octopub-productservice-cluster-ip
  labels:
    component: #{Project.Labels.Component}
spec:
  type: ClusterIP
  selector:
    component: #{Project.Labels.Component}
  ports:
    - port: 8083
      targetPort: 8083
      name: http-product